### ISSUE TITLE
Failure to handle multiple repo: inputs in search query

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#256]
### Describe the bug

The logic around grabbing the owner and repo name is breaking when attempting to handle multiple repos. 

### To Reproduce

Run the action with SEARCH_QUERY set to a string with multiple repo: entries

### Expected behavior

Proper handling of multiple repos in the search query.

**Comment by zkoppert** [comment]
```shell
Traceback (most recent call last):
  File "/Users/zkoppert/repos/issue-metrics/./issue_metrics.py", line 369, in <module>
    main()
  File "/Users/zkoppert/repos/issue-metrics/./issue_metrics.py", line 283, in main
    owner_and_repository = get_owner_and_repository(search_query)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zkoppert/repos/issue-metrics/./issue_metrics.py", line 232, in get_owner_and_repository
    result["repository"] = item.split(":")[1].split("/")[1]
```
